title: "ACM SIGMETRICS"
description: "Special Interest Group on Performance Evaluation"
url: ""
baseurl: ""
markdown: kramdown

# Build settings
plugins: []
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Navigation for header
